version: '3.8'

services:
  redis:
    image: redis:7
    container_name: api-gateway-redis
    ports:
      - "6380:6379"
    restart: always
  
  mongo:
    image: mongo:6
    container_name: api-gateway-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

  gateway1:
    build:
      context: ./ApiGateway
    container_name: gateway1
    ports:
      - "5171:80"
    environment:
      - Gateway__InstanceId=gateway-1
    depends_on:
      - redis
      - mongo

  gateway2:
    build:
      context: ./ApiGateway
    container_name: gateway2
    ports:
      - "5172:80"
    environment:
      - Gateway__InstanceId=gateway-2
    depends_on:
      - redis
      - mongo

  gateway3:
    build:
      context: ./ApiGateway
    container_name: gateway3
    ports:
      - "5173:80"
    environment:
      - Gateway__InstanceId=gateway-3
    depends_on:
      - redis
      - mongo

  monitoring:
    build:
      context: ./MonitoringService
    container_name: monitoring
    ports:
      - "5080:80"
    depends_on:
      - mongo

volumes:
  mongo-data:
